mysql: &mysql
  adapter: mysql2
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  username: "<%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>"
  password: "<%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>"
  host:     "<%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>"
  port:     "<%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>"
  socket:   "<%=ENV['OPENSHIFT_MYSQL_DB_SOCKET']%>"
  timeout: 5000

mysql_devel: &mysql_devel
  adapter: mysql2
  database: "labs_development"
  username: "tiwillia"
  host: "localhost"
  timeout: 5000

defaults: &defaults
  pool: 5
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "mysql_devel" %>

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
